import React, { Component } from 'react';
import NavBar from './Navbar'
import Navbar from './Navbar';
import '../componentStyles/Home.css'
import Search from './Search';

class Home extends Component {
  constructor(props) {
    super(props);
    this.state = {
    };
  }

  render() {
      return (
        <div>
          <Navbar/>
          <div className={"homeContainer"}>
          <Search/>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam id interdum sapien. Curabitur nec laoreet dolor. Donec pulvinar nisi sed euismod elementum. Integer elit velit, hendrerit et erat vel, commodo cursus nibh. Sed lacus dolor, varius sed egestas blandit, laoreet at purus. Donec lacinia dapibus augue, sit amet posuere risus feugiat ut. Phasellus lectus justo, consequat at dolor ut, finibus euismod eros. Nulla a est ultrices turpis tincidunt facilisis eget eu libero. Suspendisse potenti. Mauris vehicula massa vel est aliquet sagittis. Morbi tincidunt est lectus, quis consequat massa vulputate id. Ut sodales tortor ut lacus tristique, eu varius ex vulputate. Morbi nec faucibus eros. Quisque vel justo sit amet ipsum placerat porttitor sed nec velit. Integer ante metus, hendrerit a ultrices ornare, condimentum ut ex. Sed id maximus ipsum, a lacinia lacus.

Maecenas sit amet libero eu nisi vulputate porttitor. Integer non arcu sit amet felis suscipit vehicula ut ac quam. Vivamus mattis dolor sapien, ut dictum sem consequat a. Vivamus leo justo, tempus eget vestibulum in, consequat at neque. Donec nibh elit, aliquam id ullamcorper quis, consequat ut metus. Curabitur ut vehicula dolor, in vestibulum sem. Nulla eget semper quam. Maecenas ac sodales nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent dapibus, ipsum a venenatis mollis, augue erat condimentum nibh, et dignissim risus sem nec odio. Phasellus elementum ultrices nulla interdum finibus.

Nunc ac nulla id nunc ullamcorper malesuada. Ut a est ac enim congue mollis condimentum vel odio. In et eros porta, tincidunt odio ac, lacinia turpis. Suspendisse potenti. Nullam a commodo eros. Mauris suscipit sit amet sem id rutrum. Mauris auctor nisl vel eleifend dapibus. In eget consectetur magna. Proin hendrerit eros ac odio ornare ultrices. Curabitur ullamcorper pharetra posuere. Fusce lobortis orci ultricies consequat pretium. Morbi lorem quam, ultrices vitae viverra non, blandit facilisis est. Curabitur pulvinar erat vel orci mattis congue. Aliquam libero sem, pharetra id tempor a, porttitor ac dui. Etiam aliquam faucibus magna, ut rhoncus odio tincidunt nec.

Nulla tincidunt vulputate laoreet. Aliquam tempus dolor id felis varius placerat. Morbi in tortor quis nulla vulputate commodo non non odio. Phasellus eros turpis, sodales a maximus quis, condimentum non nunc. Nullam luctus purus justo, vel porta nisl fringilla quis. Mauris viverra aliquam diam, vel porttitor diam faucibus nec. Ut sed augue nec est scelerisque imperdiet a et nibh. Vivamus pretium, odio sed consequat lacinia, odio urna tempus nunc, ut vestibulum magna augue a neque. Vestibulum venenatis velit at eros dapibus, sit amet tempus tellus congue. Aenean ac mauris ut ex tempus viverra vel in arcu. Nulla facilisi. Sed dictum quis sem vitae pellentesque. Sed tempor, dolor in ultricies dapibus, dui libero luctus tortor, eget ullamcorper nunc dolor eget sem.

Suspendisse non tincidunt sapien, in lobortis dolor. Quisque eu cursus mi. Praesent vestibulum nunc quis velit aliquam sodales. Aliquam cursus libero sed mauris semper vehicula. Donec pretium, lacus eget vehicula suscipit, risus tortor ornare tellus, euismod euismod tortor tellus eu massa. Suspendisse augue quam, convallis et nulla ut, accumsan luctus risus. Maecenas pretium lacus ut auctor eleifend. Quisque eu lorem a ipsum gravida bibendum nec sit amet sem. Morbi ut vulputate lacus. Nam orci massa, dictum condimentum fermentum sit amet, finibus in ante. Aenean non leo quis enim mollis commodo. Proin convallis orci eu sem convallis dapibus. Cras eget mauris at justo blandit volutpat eget nec ex. Pellentesque tristique neque et dignissim ultrices. Ut maximus odio non augue condimentum, sit amet vulputate sapien efficitur.

Quisque mollis maximus purus in hendrerit. Cras blandit lacus eu lacus convallis, fringilla suscipit libero aliquet. In aliquet nisl enim. In at ornare lacus. Phasellus sollicitudin tellus ut ornare iaculis. Mauris ut dui at nisl pretium fringilla. Vivamus eu mi quis nibh dignissim fermentum et nec quam. Pellentesque tincidunt turpis metus, id fermentum nisi imperdiet non. Pellentesque eget facilisis metus. Mauris porttitor maximus eros quis dignissim. Proin eu mollis massa, sed tristique turpis. Nullam ullamcorper commodo mauris nec ultrices. Phasellus scelerisque enim lacus, id tempus libero elementum quis. Sed porttitor magna in felis euismod suscipit.

Praesent facilisis gravida nibh a scelerisque. Proin euismod rutrum tortor non ullamcorper. Donec vitae mauris quis diam cursus auctor. Proin vulputate sed nulla sed imperdiet. Proin massa lacus, facilisis non commodo ut, tempus id lectus. Curabitur imperdiet nibh vitae elit commodo fringilla. Cras ac consequat ligula. Aenean laoreet, nibh commodo accumsan dictum, eros odio lacinia urna, ut luctus dolor diam vitae ante. Sed in tortor metus. Sed ut mauris mauris. Nulla volutpat eu enim congue elementum. Suspendisse ullamcorper felis mi, vel sollicitudin elit dapibus vitae. Vivamus congue luctus condimentum. Sed non massa iaculis, eleifend ipsum a, pellentesque nisi. Etiam aliquet nulla ac imperdiet ultrices.

Phasellus congue varius ligula sed scelerisque. Mauris iaculis aliquam erat quis malesuada. Pellentesque vestibulum neque ligula, in consectetur lorem pretium quis. Pellentesque maximus condimentum elit, non ornare elit vestibulum ac. Ut vitae arcu sit amet lacus scelerisque ornare. Nam eleifend eu massa et blandit. Phasellus pellentesque, elit vitae gravida finibus, odio nibh molestie augue, nec ultricies risus dui id tellus.

Phasellus nec mattis lectus, vitae ultricies enim. Nulla aliquam ornare diam eu euismod. Donec tincidunt tortor eget sapien dapibus viverra. Nam at consectetur felis. Vivamus luctus enim ut odio faucibus, quis pharetra sem finibus. In convallis vitae orci vel elementum. Ut scelerisque dui eu ligula facilisis porta. Integer nec mi eget ante congue finibus. Sed nec nisl erat.

Aliquam cursus dolor nec quam finibus, quis laoreet diam dignissim. In hac habitasse platea dictumst. Vestibulum est tellus, cursus quis arcu pulvinar, ornare sagittis massa. Mauris non sapien sit amet urna condimentum volutpat. Etiam eu vestibulum ipsum, sed cursus ligula. Duis ut pulvinar nunc. Integer fringilla facilisis tortor eu varius. Vestibulum faucibus sem ac nunc fringilla, non varius elit gravida. Maecenas porttitor purus vel lectus ullamcorper sollicitudin. Nam id ex et leo bibendum euismod ut ac nisl. Maecenas tristique sodales velit, vel varius orci consequat at. Phasellus fringilla magna metus, eget gravida justo dignissim sed.

Maecenas venenatis sollicitudin mi, et viverra mi pellentesque id. Suspendisse faucibus ipsum purus, vel bibendum diam rutrum a. Donec vehicula velit eu urna consectetur venenatis. Donec sed augue nec velit ornare dignissim. Sed porta metus nisl, vel auctor velit gravida porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum egestas massa non consectetur sollicitudin.

Maecenas dapibus purus non suscipit rutrum. Aliquam maximus tempor orci. Donec eget tincidunt libero. Duis non massa felis. Proin id arcu sagittis, mattis ipsum quis, scelerisque lectus. Vestibulum nec risus laoreet sem placerat auctor eget eget lacus. Vestibulum volutpat sapien urna, ut rhoncus nunc aliquet non. Donec eleifend luctus eros, ac rutrum nibh sodales nec. Quisque nec gravida ex. Nam sagittis fringilla sem. Curabitur quis augue lectus.

Ut non rhoncus justo. Integer purus est, condimentum ut tristique id, accumsan sed ligula. Integer a leo et urna pulvinar bibendum. Aliquam tristique egestas aliquam. Phasellus quis orci ligula. In non nibh diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed hendrerit iaculis condimentum. Curabitur id posuere libero. Mauris luctus orci ac nisl blandit placerat.

Vestibulum nibh nisi, posuere et massa ac, pharetra fermentum eros. Aenean non nisl in leo accumsan iaculis eu non leo. Pellentesque at rhoncus ante. In fermentum est vitae nisl eleifend, a maximus massa dignissim. Maecenas nisi ligula, consectetur sed sapien rutrum, efficitur mollis felis. Nulla vestibulum sollicitudin purus eu convallis. Etiam et ex blandit, ornare erat ac, sollicitudin lectus. Nunc dictum cursus enim, eget bibendum augue rutrum a. Curabitur quis ligula volutpat, vulputate neque vitae, varius orci. Donec sollicitudin nisl et justo sodales elementum. Suspendisse nec lacus dolor. Nam malesuada odio eget lacus tincidunt convallis. Proin quam nunc, tempus sit amet dolor vitae, rutrum suscipit turpis. Vestibulum commodo nunc in cursus efficitur. Aenean ullamcorper arcu vitae orci efficitur sagittis.

Integer vitae felis nec erat auctor aliquam in consectetur odio. Duis metus eros, varius eu vestibulum non, convallis id sapien. Fusce sed sagittis nisl. Pellentesque sit amet nunc tortor. Suspendisse tincidunt, diam sed rhoncus eleifend, diam turpis tempus diam, non vestibulum dolor ipsum id ante. Proin sit amet erat vitae nisi dictum condimentum eu sed eros. Pellentesque hendrerit mauris eu imperdiet ultrices. Suspendisse egestas elementum fringilla. Maecenas porta odio turpis, vel eleifend ante congue et. Duis auctor est ac mattis iaculis.

Praesent placerat sollicitudin turpis, in iaculis diam efficitur et. Morbi ultricies suscipit eros, at pellentesque sem vulputate nec. Nunc vehicula convallis tellus, ac dignissim mauris commodo vitae. Praesent a mollis turpis. Ut vulputate sodales purus in pellentesque. Nullam posuere eget sapien sed commodo. Ut aliquet dolor et porta ultricies. Aliquam erat volutpat. Vivamus lorem est, varius sit amet tempus a, pretium quis justo. Mauris id lectus turpis. Mauris vitae facilisis lacus. Morbi efficitur tellus ac orci molestie euismod. Praesent ornare enim sit amet lectus imperdiet dapibus.

Ut semper ultrices nunc sed viverra. Nulla facilisi. Vivamus molestie turpis at sodales aliquet. Nam ac hendrerit risus. Duis varius dui velit, sollicitudin sagittis ipsum rhoncus in. In eget odio vitae mauris ultrices imperdiet. Vivamus euismod et sem eu viverra. Nullam scelerisque orci nec efficitur bibendum. Ut nec tempus est.

Fusce feugiat ornare neque quis fringilla. Proin turpis nulla, consectetur et iaculis et, molestie id tellus. Vestibulum a tristique eros. Ut finibus, diam ac feugiat vehicula, mauris orci congue sem, at egestas urna sem ac orci. Sed dui enim, pharetra nec egestas nec, consequat nec odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut ultrices diam. In turpis enim, sollicitudin in fermentum id, tempor et turpis. Etiam odio dolor, dictum quis suscipit nec, rhoncus eget sapien.

Praesent facilisis iaculis lacus. Cras ut convallis augue, eu aliquam ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam at porta libero. Sed egestas ex lorem, sed ullamcorper nisl feugiat at. Aenean sed tincidunt augue, feugiat varius orci. Morbi feugiat, risus vel lobortis tristique, purus purus interdum sem, id semper tellus leo id nisi. Quisque ante diam, lacinia at vulputate in, faucibus quis ex. Nulla interdum fringilla sapien sit amet rhoncus. Quisque vestibulum lacus nec eleifend hendrerit.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris congue, enim a iaculis tempor, urna libero fermentum lorem, id commodo quam sem nec nulla. Fusce dolor ante, tincidunt euismod semper et, luctus ut ligula. Donec at volutpat massa. Duis non ullamcorper dui, a aliquam mauris. Aenean sed porta mi. Pellentesque eu massa id leo ultricies euismod. Vivamus nisl mi, eleifend ut ipsum quis, pulvinar laoreet enim. Pellentesque feugiat faucibus enim, in faucibus neque blandit nec. Sed ac tortor sed quam suscipit volutpat. Ut massa lacus, egestas consequat blandit vel, tristique ut libero. Quisque ex est, semper a mattis non, blandit in lorem. Ut id molestie dui, ullamcorper volutpat nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ac mauris a est consectetur congue vitae vitae tortor.

Vivamus felis nulla, ullamcorper eget euismod ut, blandit mattis ipsum. Quisque eget tristique lectus. Integer gravida nisl vitae quam aliquet porta. Pellentesque quis facilisis ante. Nam eu dui sed odio egestas bibendum a eget nibh. Donec fringilla justo ut nisl pulvinar, et volutpat lacus viverra. Duis nibh risus, fringilla vel est at, interdum ultrices libero. Nullam ultrices euismod dignissim. Aliquam dignissim turpis nisi. Morbi hendrerit tempus semper. Donec mollis lacinia magna, vitae condimentum elit eleifend eu.

Maecenas ut elit eu orci euismod auctor at id purus. Proin dictum sapien id ultricies varius. Vivamus nec volutpat libero, ut molestie velit. Mauris eu lacus hendrerit, suscipit diam quis, auctor metus. Duis ac enim facilisis, sodales elit sed, euismod ligula. Ut velit lectus, cursus sit amet est nec, blandit ullamcorper tortor. Duis risus neque, eleifend quis sem ac, aliquam suscipit elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque vestibulum neque nec enim mattis facilisis. Ut eros tellus, molestie vitae arcu in, pulvinar suscipit risus. Mauris eros dolor, feugiat et pretium id, feugiat vitae dui. Duis vitae magna non lectus malesuada molestie. Morbi vitae massa placerat, varius neque eget, luctus eros.

Curabitur augue libero, posuere non molestie id, aliquam a augue. Mauris ipsum nulla, imperdiet vel commodo at, venenatis euismod diam. Vivamus sed tortor placerat, fringilla est eu, pulvinar metus. Suspendisse sollicitudin quis sem ac viverra. Cras nibh felis, condimentum vel leo ut, tempus luctus libero. Aenean vel nibh a eros tempus elementum. Nam eu tincidunt dolor, eu dignissim lacus. Quisque sit amet ipsum arcu. Suspendisse vitae lacus feugiat, pharetra enim sed, eleifend ex. Nunc luctus hendrerit mauris vel dignissim. Cras ut fringilla enim. Suspendisse consequat enim et feugiat luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque suscipit a leo eu porta.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin et ipsum non est semper mattis a quis dui. Praesent scelerisque mollis justo vitae condimentum. Curabitur bibendum lacus vitae nunc iaculis tincidunt id ultricies ante. Aenean sollicitudin auctor libero, ac egestas turpis fermentum semper. Donec volutpat dictum libero, eget mollis tellus pretium in. Sed faucibus lobortis egestas.

Sed interdum nunc ac diam viverra tincidunt. Vestibulum hendrerit, nulla sed blandit ornare, ipsum nisl iaculis urna, a cursus nulla mauris sed leo. Duis auctor ipsum velit, non vulputate dui euismod non. Integer et neque tellus. Morbi a mauris ligula. Donec non tortor finibus, viverra nisi sed, luctus tortor. Aliquam hendrerit feugiat pulvinar.


          </div>
        </div>
      )
  }
}

export default Home;
